### ISSUE TITLE
examples/editor -- image moves when window is dragged

### ISSUE THREAD

**Issue by cos1110** [raylib-extras/rlImGui#11]
https://github.com/raylib-extras/rlImGui/blob/4fab9162afee51d279e6e1317b8b008ccd6a77c5/examples/editor.cpp#L65

When the image editor window is dragged around it results into the image getting move as well. This fix is better to prevent that.
`
Focused = ImGui::IsItemHovered() == false && ImGui::IsWindowFocused(ImGuiFocusedFlags_RootAndChildWindows);
`

**Comment by JeffM2501** [comment]
Thank you for pointing out this problem.

I don't feel this is the correct fix, as a window can be left in the focused state when it is not hovered.

I have updated the example with a better fix that tracks the screen space content area of the window and doesn't apply the update when the drag is outside of the content area.

**Comment by cos1110** [comment]
Now things will work great. Thanks.
