### ISSUE TITLE
Dear Bindings?

### ISSUE THREAD

**Issue by RobLoach** [raylib-extras/rlImGui#13]
Would this be helpful for the raylib integration? https://github.com/dearimgui/dear_bindings

**Comment by JeffM2501** [comment]
not really. The integration isn't a binding. It doesn't wrap up ImGui in any way.
rlImGui is more like a raylib backend for Dear ImGui. 
It works in two very simple steps

1) Tells ImGui when to start a frame and fills out all the input stuff
2) Tells ImGui when a frame is done, and then draws all the geometry and textures that make up the GUI.

The rest of ImGui doesn't need to be wrapped up or interact with raylib in any way. 

This tool is more for helping other languages bind to ImGui itself, not the backend.

**Comment by RobLoach** [comment]
Very cool! Thanks for the explanation :+1:
