### ISSUE TITLE
copy/paste issue in code with key event

### ISSUE THREAD

**Issue by ypujante** [raylib-extras/rlImGui#23]
The code here: https://github.com/raylib-extras/rlImGui/blob/fcb54869a90d84c6a6306a43127214a767d77428/rlImGui.cpp#L165

and here: https://github.com/raylib-extras/rlImGui/blob/fcb54869a90d84c6a6306a43127214a767d77428/rlImGui.cpp#L175

clearly contains a copy/paste issue:

```cpp
// line 163
	bool shiftDown = rlImGuiIsShiftDown();
	if (shiftDown != LastShiftPressed)
		io.AddKeyEvent(ImGuiMod_Shift, ctrlDown); // COPY/PASTE ISSUE
	LastShiftPressed = shiftDown;

// line 173
	bool superDown = rlImGuiIsSuperDown();
	if (superDown != LastSuperPressed)
		io.AddKeyEvent(ImGuiMod_Super, ctrlDown); // COPY/PASTE ISSUE
	LastSuperPressed = superDown;

**Comment by JeffM2501** [comment]
Can you submit a PR for this fix please?

**Comment by ypujante** [comment]
I just told you exactly what is wrong. The fix is obvious. It will be a lot easier for you to simply fix it. I am not sure why you closed the issue before it is actually fixed.
