### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by xzripper** [raylib-extras/rlImGui#25]
Running ```premake-mingw.bat``` generates .make files, but it's not possible to import them. Running ```make``` shows an error: unable to find ```raudio.c```. Including raw ```rlImGui.h``` shows a lot of errors when compiling. How to build static library and include file (like include/raylib.h, lib/raylib.a)?

**Comment by xzripper** [comment]
Also ```premake-mingw.bat``` can't find raylib, when I have already compiled static library, include file, and raylib installed using installer.

**Comment by JeffM2501** [comment]
It sounds like you are using a version of mingw that is too old (like version 6.3). raylib does not build with that old of a mingw.

The premake system is not designed to use an existing install of raylib. 

You do not have to use the premake system to use this library, simply add the files to your existing build system. The premake setup is just to help build the examples standalone. It is not required in any way.
