### ISSUE TITLE
How to add flags and title to window?

### ISSUE THREAD

**Issue by xzripper** [raylib-extras/rlImGui#26]
To add flags and title to window in ImGui, you can use: ```ImGui::Begin("Window", 0, ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize);```, but there is no any arguments to do it in rlImGui.

**Comment by JeffM2501** [comment]
rlImgui doesn't change how the ImGui windows work. You still call ImGui::Begin to create an ImGui window inside of the raylib window.
Look at the examples, they call ImGui::Begin.
