### ISSUE TITLE
Crashes on hotreload enviroment.

### ISSUE THREAD

**Issue by marcosantos98** [raylib-extras/rlImGui#27]
Hi! While trying to use rlImGui on a hotreloadable enviroment, where the game code is loaded dynamically, the following line triggers an assert in glfw on call to `glGetFramebufferSize`.

https://github.com/raylib-extras/rlImGui/blob/d89083021bbf9eadefb5a307154f99e421c4901f/rlImGui.cpp#L94

```cmd
Assertion failed: window != NULL, file ${LOCAL_PATH}/glfw/src/window.c, line 694
```

The solution was replacing the call to `glfwGetFramebufferSize` with:
```C
width = rlGetFramebufferWidth();
height = rlGetFramebufferHeight();
```

Currently is working fine on my specific project, so I don't know if this is an actual issue or not.

Keep the good work. ❤️

**Comment by JeffM2501** [comment]
I have pushed these change sup, thank you.

**Comment by JeffM2501** [comment]
I am reverting this change, it does not work properly with resizable windows. That is more important than supporting a hot reload system.
