### ISSUE TITLE
Cmake Build config?

### ISSUE THREAD

**Issue by hero2002** [raylib-extras/rlImGui#3]
why not use cmake since raylib use it?

**Comment by JeffM2501** [comment]
1) The cmake in raylib was contributed by a third party and not maintained by ray, this makes me hesitant to build on top of it.
2) I feel premake is much lighter weight than cmake. Premake doesn't use a domain specific language and is much easier to use.
3) I don't like cmake or know how to use it.

**Comment by hero2002** [comment]
I am not that good in cmake too but a serious library need one
```cmake
cmake_minimum_required (VERSION 2.8.12)
project(rlImGui LANGUAGES CXX)
file(GLOB SOURCE_FILES3 
	*.cpp
	*.c
	imgui/*.cpp
)
file(GLOB HEADER_FILES3 
	*.h
	/imGui/*.h
	/extras/**.h
	/raylib/src/**.h	
)
add_library (rlImGui STATIC ${SOURCE_FILES3})
```

**Comment by JeffM2501** [comment]
This is not a library, it's a few files you can include into your project. The premake is just to help build the examples.

**Comment by hero2002** [comment]
not sure I see what the problem on handling it as lib but no problem, also this way should be easier to include imgui since imgui doesn't have cmake file

**Comment by beetaa** [comment]
> I am not that good in cmake too but a serious library need one this one works, I tested it
> 
> ```cmake
> cmake_minimum_required (VERSION 2.8.12)
> project(rlImGui LANGUAGES CXX)
> file(GLOB SOURCE_FILES3 
> 	*.cpp
> 	*.c
> 	imgui/*.cpp
> )
> file(GLOB HEADER_FILES3 
> 	*.h
> 	/imGui/*.h
> 	/extras/**.h
> 	/raylib/src/**.h	
> )
> add_library (rlImGui STATIC ${SOURCE_FILES3})
> ```

thank you for your code. I tried but have a little problem because of the header files not found. I adjust a little as below, and compile success. FYI.

```
cmake_minimum_required (VERSION 2.8.12)
project(rlImGui LANGUAGES CXX)
file(GLOB SOURCE_FILES3 
	*.cpp
	*.c
	imgui/*.cpp
)
include_directories(imgui extras raylib/src)
add_library (rlImGui STATIC ${SOURCE_FILES3})
```

1. save the code as `CMakeLists.txt`
2. run `cmake -G "MinGW Makefiles"`
3. run `make`

all done. hope helps.

**Comment by JeffM2501** [comment]
Thank you for the work, but I still feel cmake is unneeded for this project.
1) I can't maintain cmake (raylib has the same problem)
2) This project has a single source file, so calling it a 'library' is a stretch. I would prefer people to just add the source file to whatever build system they are using. Premake is simply used as a way to test the code.

**Comment by ARoxdale** [comment]
The project really needs just a regular makefile. Premake5 is unavailable in ubuntu repos. And premake is pretty obscure to begin with. At least consider downgrading to premake4 or else just use a regular makefile.

**Comment by JeffM2501** [comment]
the repo comes with premake5, you don't need a package for it.
