### ISSUE TITLE
GetMouseRay() does not work properly

### ISSUE THREAD

**Issue by copark86** [raylib-extras/rlImGui#30]
I was trying to make some point-picking example code using GetMouseRay but it acted weirdly.

I just ported the following raylib example to the editor example to see if I can use a mouse click to pick a cube.
https://github.com/raysan5/raylib/blob/master/examples/core/core_3d_picking.c

It works somehow but there is some sort of mismatch between the clicked point that causes the trigger and the cube location on the screen. Probably, GetMousePosition() is not working properly.

It looks simple to fix though.

Just wondering if anyone already solved this problem.

**Comment by JeffM2501** [comment]
This is similar to your other issue. Raylib and ImGui are NOT integrated. GetMouseRay when combined with GetMousePosition works in screen space and has no idea about an ImGui window.
You have to write code to transform the screen space mouse position into a local space for the render texture you are using to draw in your editor.

You can get the window position from ImGui and offset the mouse pos by that to be in window space, then pass that to GetMouseRay.

Also note that render textures are upside down from the screen so you'll need to flip the Y of your mouse pos before you get the ray for it.
