### ISSUE TITLE
Trying to load custom font by default

### ISSUE THREAD

**Issue by hka** [raylib-extras/rlImGui#32]
In commit: c71a02530ce951523d794eacb84a209fc4fccda4

This got commited:
io.Fonts->AddFontFromFileTTF("resources/fa-solid-900.ttf", FONT_AWESOME_ICON_SIZE, &icons_config, nullptr);
//io.Fonts->AddFontFromMemoryCompressedTTF((void*)fa_solid_900_compressed_data, fa_solid_900_compressed_size, FONT_AWESOME_ICON_SIZE, &icons_config, icons_ranges);

it should probably be just the commented row and delete the other one:
io.Fonts->AddFontFromMemoryCompressedTTF((void*)fa_solid_900_compressed_data, fa_solid_900_compressed_size, FONT_AWESOME_ICON_SIZE, &icons_config, icons_ranges);

**Comment by JeffM2501** [comment]
This has been fixed. Thanks for reporting it.
