### ISSUE TITLE
Weird interactions with rlImgui and SUPPORT_CUSTOM_FRAME_CONTROL=1

### ISSUE THREAD

**Issue by WildRackoon** [raylib-extras/rlImGui#33]
While following [](https://github.com/raysan5/raylib/blob/master/examples/core/core_custom_frame_control.c)
Using both `PollInputEvents()` and `SwapScreenBuffer()`
And using rlImgui's `simple.cpp` example

- I witnessned that fps counting was not working ( frozen at 0.0 fps)
- Animated widgets do not work anymore(e.g the plotting section)

I believe both issues are due to `io.DeltaTime` being 0 since `GetFrameTime()` is invalidated and cannot be used anymore when `SUPPORT_CUSTOM_FRAME_CONTROL` is on. 
Using raylib's `GetTime()` and checking how other imgui's backends do it should be enough to fix it, I will experiment later.

Here is the full code:
```
#include "raylib.h"
#include "raymath.h"

#include "imgui.h"
#include "rlImGui.h"

int main(int argc, char* argv[])
{
	// Initialization
	//--------------------------------------------------------------------------------------
	int screenWidth = 1280;
	int screenHeight = 800;

	SetConfigFlags(FLAG_MSAA_4X_HINT | FLAG_VSYNC_HINT);
	InitWindow(screenWidth, screenHeight, "raylib-Extras [ImGui] example - simple ImGui Demo");
	rlImGuiSetup(true);

	// Main game loop
	while (!WindowShouldClose())    // Detect window close button or ESC key
	{
		PollInputEvents(); // SUPPORT_CUSTOM_FRAME_CONTROL
	
		BeginDrawing();
		ClearBackground(DARKGRAY);

		// start ImGui Conent
		rlImGuiBegin();

		// show ImGui Content
		bool open = true;
		ImGui::ShowDemoWindow(&open);

		// end ImGui Content
		rlImGuiEnd();

		EndDrawing();
		
		SwapScreenBuffer(); // SUPPORT_CUSTOM_FRAME_CONTROL
		//----------------------------------------------------------------------------------
	}
	rlImGuiShutdown();

	// De-Initialization
	//--------------------------------------------------------------------------------------   
	CloseWindow();        // Close window and OpenGL context
	//--------------------------------------------------------------------------------------

	return 0;
}
```

**Comment by WildRackoon** [comment]
Opened PR #34

**Comment by JeffM2501** [comment]
I see the PR and understand what what you are tryin to do, but I think a simpler way is to pass in the DT from outside, then it can come from any source. I've pushed up a change that adds a begin that takes a custom DT.

**Comment by WildRackoon** [comment]
Fine by me!

I agree that if user code manually triggers frames with its own time computation, ImGui should not also compute its own and end up with disrespectancies
