### ISSUE TITLE
Touchscreen input doesn't dispatch correctly on the web.

### ISSUE THREAD

**Issue by alberttxu** [raylib-extras/rlImGui#38]
Hello,

I am using rlImGui in a web app which is compiled using emscripten. I noticed that on mobile devices (my iphone and ipad), touch events are sent to the main raylib app and not Dear ImGui. On desktop devices with a real mouse I don't see any problems. I am not very familiar with the ImGui internals so any advice would be appreciated.

Thank you.

**Comment by JeffM2501** [comment]
ImGui (and thus rlImGui by extension), is made for a mouse/keyboard interface. It has no native touch support. If you want to try to add some kind of touch mapping, you can do that, but you'll have to make some choices for how you want to map touch inputs to mouse/keyboard inputs.
You'd make changes in `rlImGuiNewFrame `and use the touch input functions from raylib set the mouse position and button states in in the ImGuiIO structure. 
Note that none of this will enable things like touch keyboards when input is selected, you'd have to hook that up yourself.

ImGui was designed as a tooling GUI, so it's not really setup for this kind of work, but I'm sure you can find some way to make it work, but this is out of scope for what rlImGui can do for you.
