### ISSUE TITLE
Text input from imgui isnt working

### ISSUE THREAD

**Issue by CitroenGames** [raylib-extras/rlImGui#39]
the imgui demo window text input crashes the whole app.
even if i make a text input my self the whole thing crashes.

**Comment by JeffM2501** [comment]
Can you provide more information about the crash? What version of raylib and ImGui are you using?

**Comment by CitroenGames** [comment]
i will do more research and will come back with a new issue if necessary

**Comment by JeffM2501** [comment]
Got some more info on this and was able to find the problem. It has been fixed in current rlImGui code.
