### ISSUE TITLE
Headers should use include guards rather than "#pragma once"

### ISSUE THREAD

**Issue by marinedalek** [raylib-extras/rlImGui#4]
Per this C++ core guideline: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-guards
#pragma once is dissuaded as it is a nonstandard extension with no guarantee of cross-compiler compatibility. The preferred method is still include guards for standard C++. I've created a pull request with the necessary changes!

**Comment by JeffM2501** [comment]
Ate there any real compilers that don't support #pragma once?

**Comment by marinedalek** [comment]
Whether a compiler does or does not support #pragma once isn't the only consideration. It's that #pragma once can mean "include this specific file, at this path, once", whereas include guards mean "Include this text once"; if a file exists in more than one location for whatever reason, a compiler may happily include it again, because it's not the "same" file. See [https://en.wikipedia.org/wiki/Pragma_once#Caveats](url)

**Comment by JeffM2501** [comment]
I'm less concerned about that case and more concerned about maintainability and copies of the file using the same guard define. I understand the concerns with once and am willing to accept them. I do not feel that removing them will have any material impact. No user has reported an issue with current code.

Thank you for doing the research.
