### ISSUE TITLE
ImGui::IsMouseReleased not working

### ISSUE THREAD

**Issue by Lecrapouille** [raylib-extras/rlImGui#40]
Hi!

`ImGui::IsMouseReleased(ImGuiMouseButton_Middle)` is not working. I think in  `static void ImGuiNewFrame(float deltaTime)` missing code:

```
    io.MouseReleased[0] = IsMouseButtonReleased(MOUSE_LEFT_BUTTON);
    io.MouseReleased[1] = IsMouseButtonReleased(MOUSE_RIGHT_BUTTON);
    io.MouseReleased[2] = IsMouseButtonReleased(MOUSE_MIDDLE_BUTTON);
```

While this patch seems not fixing for me.

**Comment by JeffM2501** [comment]
I agree it's not working, but that's not the right fix. As of ImGui 1.8.7 we are not supposed to write to those values in the IO structure. What is missing is calls to AddMouseButtonEvent. I will work on it.

**Comment by JeffM2501** [comment]
The mouse system has been moved to events, this should resolve this issue.
