### ISSUE TITLE
Window rendering artifacts when using FLAG_RESIZABLE

### ISSUE THREAD

**Issue by sketchyscribe** [raylib-extras/rlImGui#47]
In testing out the example projects on my machine, if the FLAG_RESIZABLE raylib config flag is set, ImGui windows have a split about a third of the way from the top, and only seem to render within the bounds of a smaller size that the actual window size, starting from the bottom left of the screen.

This is the compiled from the "imgui_style_example.cpp", using the master branch of ImGui.
Maximized window
![Screenshot 2023-12-10 145454](https://github.com/raylib-extras/rlImGui/assets/95104570/ae8b9de2-4cc5-4a55-85b9-924e0719d502)
Window at starting resolution.
![Screenshot 2023-12-10 145616](https://github.com/raylib-extras/rlImGui/assets/95104570/5ddeb9d6-441b-450c-92ca-dbbab52f26da)

I'm compiling with MingW on Windows 11.

**Comment by JeffM2501** [comment]
This looks like a scissor issue. 
I fixed an issue with the scissor system just today and I'm not seeing the issue in current code.
Can you verify you have current code? I've made the simple example resizeable in hopes that it can show the issue.

**Comment by sketchyscribe** [comment]
Just cloned the latest commit, I definitely should've check to see if there was one first, but it seems it's still happening.  I might just be building wrong, this is my Makefile, maybe there some insight.
 
 ```
 # Compiler Flags
CC	= g++
CFLAGS 	= -std=c++17 -w -Wl,-subsystem,windows

# Project Files
RAYLIB_DIR 	= C:/dev/raylib/src
IMGUI		= C:/dev/imgui
RLIMGUI		= C:/dev/rlimgui

SRC	= src/*.cpp
SRC	+= $(IMGUI)/imgui.cpp $(IMGUI)/imgui_demo.cpp $(IMGUI)/imgui_draw.cpp $(IMGUI)/imgui_tables.cpp $(IMGUI)/imgui_widgets.cpp $(RLIMGUI)/rlImGui.cpp 
INCLUDE = -Iinclude -I$(RAYLIB_DIR) -I$(IMGUI) -I$(RLIMGUI)
LIB	= -Llib -L$(RAYLIB_DIR) -lraylib -lopengl32 -lgdi32 -lwinmm
EXE 	= game
OUT	= bin

# Debug build settings
DDIR	= $(OUT)/debug
DEXE	= $(DDIR)/$(EXE)_debug.exe
DFLAGS = -g -O0

# Release build settings
RDIR	= $(OUT)/release
REXE	= $(RDIR)/$(EXE).exe
RFLAGS	= -O3

all: clean debug

debug: $(SRC)
	mkdir -p $(OUT)
	$(CC) $(SRC) -o $(DEXE) $(INCLUDE) $(LIB) $(CFLAGS) $(DFLAGS)
	./$(DEXE)

clean:
	rm -f $(DEXE) $(REXE) 
 ```

**Comment by sketchyscribe** [comment]
After some more testing, I'm assuming this is just a problem with my setup somehow, as I noticed in another project that when I use the raylib gif recording is only displays the gif in the same area that's getting cut weirdly, so most likely something wrong with my raylib setup somehow.

**Comment by JeffM2501** [comment]
If you have a high DPI display that is running with some display scaling, make sure you have enabled high DPI mode. Also verify that you have current video drivers for your GPU.
