### ISSUE TITLE
Scissor or viewport issue with ImGui on Windows

### ISSUE THREAD

**Issue by Neolisk** [raylib-extras/rlImGui#53]
See screenshots. Running the provided editor and simple examples exhibit a bug that looks scissor or viewport related, where part of the imgui render is cropped off. This cropping is related to where the imgui boxes are in the application window - if I move the box all the way to the top left corner, nothing is cropped.
This appears related to the fix for this issue:
https://github.com/raylib-extras/rlImGui/issues/50
If I checkout 5c49511, the issue does not occur and both the editor and simple examples display correctly.
The screenshots show the correct rendering with hash 5c49511 and the bug in the latest version.

![Screenshot 2024-01-10 100244](https://github.com/raylib-extras/rlImGui/assets/1310268/01756cdd-55c1-494f-b4c2-a4c146b67927)
![Screenshot 2024-01-10 100619](https://github.com/raylib-extras/rlImGui/assets/1310268/81e63fa6-ecad-4abe-aa11-6229ebdd47ce)

**Comment by Pantong51** [comment]
I'm getting a similar issue. My desktop is 4k, If i don't have the raylib option set "high dpi" text is unrenderable. setting it breaks once i try to render an image from raylibs render target to imgui

**Comment by JeffM2501** [comment]
I have pushed a change that should resolve it. I was finally able to duplicate the issue. It now only applies the scale if the window is in high DPI mode. Please test it out and let me know if that fixes it for you.

**Comment by Pantong51** [comment]
Will try it out tonight, the code looks like it should work, and I almost got that. Thanks for the timely response. If it does not work I'll show a video of what I'm experiencing. Or make a standalone project for you.
