### ISSUE TITLE
rlImGuiShutdown() causes SEGMENTATION FAULT

### ISSUE THREAD

**Issue by leolamarra** [raylib-extras/rlImGui#55]
## System

- Pop! Os 22.04 LTS
- CLion 2023.3.2
- CMake 3.27.8
- C++ 17
- Raylib 5.0 with internal GLFW and OpenGL 3.3 (compiled as a static library)
- Latest rlImGui version

## Issue
When closing the application the terminal reads:

> INFO: Window closed successfully
> 
> Process finished with exit code 139 (interrupted by signal 11:SIGSEGV)

The app runs just fine apart from this.

## More information
Debugging I discovered that the error is thrown at line 475 of rlImGui.cpp: `ImGui::DestroyContext();`, so `ImGui_ImplRaylib_Shutdown();` executes without problems

**Comment by JeffM2501** [comment]
Does this happen in one of the examples or your own code. There is an order dependence when you shutdown rlImGui and raylib. You must shutdown rlImGui before you shutdown raylib, since rlImGui is going to unload a texture from the GPU using raylib.

I can't duplicate this in current code, so I'll need to know more about how you are calling rlImGui and raylib.

**Comment by leolamarra** [comment]
Order is correct, code is public (all the rlImGui code is in main.cpp) [GdC2024](https://github.com/leolamarra/GdC2024).
Can't really check with the exaples now, Ill'update as soon as I can

**Comment by JeffM2501** [comment]
I can not duplicate the issue with your code, unless rlImGuiShutdown is somehow called twice..

the high level rlImGui API maintains a context as GlobalContext and that should be valid. You will need to debug into the rlImGui and ImGui code and see if that context is bad.

I am adding a null set and check to that code to help prevent double calls, but I see nothing that would cause the error.

**Comment by JeffM2501** [comment]
I see the problem now. fixing.

**Comment by JeffM2501** [comment]
fixed in commit 165a715
