### ISSUE TITLE
Could you mind adding PLATFORM_DRM support on Linux in raylib_premake5.lua ?

### ISSUE THREAD

**Issue by VisionShilin** [raylib-extras/rlImGui#56]
Could you mind adding PLATFORM_DRM support on Linux in raylib_premake5.lua ?

**Comment by JeffM2501** [comment]
I do not have a device that supports that, so I would not be able to test it. The premake system that is part of rlImGui is just provided as a simple way to to build the examples on desktop and for testing. rlImGui is a very small library (one cpp file), you can add it to any existing build system you have for any platform.
