### ISSUE TITLE
Regression: Missing text in main menu and menu is truncated

### ISSUE THREAD

**Issue by Lecrapouille** [raylib-extras/rlImGui#60]
Hi, tested on Mac Os X ~~(probably same issue for Linux)~~. This is used to work (I do not remember which old SHA1 but > 6 months)

```
    if (ImGui::BeginMainMenuBar()) {
        if (ImGui::BeginMenu("File")) {
            if (ImGui::MenuItem("New", nullptr, false)) {
```

Here screenshots:

- Under "Petri net" tab, no menu is displayed (shall be "File Actions Help")
<img width="458" alt="Capture d’écran 2024-04-14 à 5 49 29 PM" src="https://github.com/raylib-extras/rlImGui/assets/17874458/6344d6d9-5d03-43b6-9c4e-f4de706b8a56">

- When clicking on the menu, not all menu is shown

<img width="458" alt="Capture d’écran 2024-04-14 à 5 51 19 PM" src="https://github.com/raylib-extras/rlImGui/assets/17874458/82c6266f-4cd4-4411-9499-af2383f0f760">

-  Here is the expected behavior (done with GLFW3)

<img width="348" alt="Capture d’écran 2024-04-14 à 7 08 45 PM" src="https://github.com/raylib-extras/rlImGui/assets/17874458/40cd1abd-85fc-49cc-a4c2-f3e222187aca">

**Comment by JeffM2501** [comment]
did you create your raylib window with the high DPI flag enabled?

**Comment by Lecrapouille** [comment]
@JeffM2501 Do you mean this:

```
    m_screen_resolution.x = 0.0f;
    m_screen_resolution.y = 0.0f;
    m_screen_resolution.width = int(width);
    m_screen_resolution.height = int(height);

    SetConfigFlags(FLAG_WINDOW_RESIZABLE | FLAG_WINDOW_HIGHDPI);
    InitWindow(m_screen_resolution.width, m_screen_resolution.height, title.c_str());
```

?

**Comment by JeffM2501** [comment]
yes, does anything change if you remove that flag?
It has been hell supporting the mac with it's high DPI flag, it does not behave the same as other platforms with regard to the stencil buffer and it cuts off things. The mac OpenGL driver is very buggy and inconsistent in the way.

**Comment by Lecrapouille** [comment]
I've commented the flags, same issues.

**Comment by Lecrapouille** [comment]
Strangely the online version (raylib + emscripten) seems not affected https://lecrapouille.github.io/TimedPetriNetEditor/TimedPetriNetEditor.html (clicks are not working since an update of your lib that I forget to report) in the case you want to reproduce here the complete code https://github.com/Lecrapouille/TimedPetriNetEditor

you have to comment the backend https://github.com/Lecrapouille/TimedPetriNetEditor/blob/d2dd328ffcd64c867420fc5cdc7662cf9e8bfaea/Makefile#L10 to switch between glfw3 and raylib backend for dear imgui.

```
git clone https://github.com/Lecrapouille/TimedPetriNetEditor --recursive
cd TimedPetriNetEditor/
make download-external-libs
make compile-external-libs
make -j8
```

`make download-external-libs` follows the HEAD of each repo (I should fix SHA1 instead) and replace the older folder. https://github.com/Lecrapouille/TimedPetriNetEditor/blob/master/external/download-external-libs.sh

**Comment by JeffM2501** [comment]
Yes, the web version does not use OpenGL, it uses WebGL, and that gets implemented by the browser on the mac, and is implemented using metal, so it doesn't use the OpenGL driver apple provides.

I don't have a mac to test this. 

The stencil and high DPI stuff has gone back and forth to try and make it work for macs and not macs, but at this point I can't make any mac specific changes for it since I can't test.
