### ISSUE TITLE
Render outside the window?

### ISSUE THREAD

**Issue by HermesonBF** [raylib-extras/rlImGui#67]
I am creating a tool using Raylib + rlImGui, but I would like to be able to draw a ImGui window outside the main window of Raylib so the users can use multiple monitors, is it possible to do that? I thought about creating a new window on another thread using OpenGL + ImGui just to draw one window and interfacing with it somehow from the Raylib main window for communication but I wonder if there is a better way.

**Comment by JeffM2501** [comment]
Raylib only supports one window, So this is not possible with raylib or rlImGui.
So yes, you'd have to to handle all that yourself outside of raylib and rlImGui.
