### ISSUE TITLE
Problem with docking support

### ISSUE THREAD

**Issue by HermesonBF** [raylib-extras/rlImGui#68]
Can an example be provided on how to use docking + rendering things with Raylib? For some reason when docking is enabled it erases things in the background so the Raylib rendered stuff does not appear in the screen (same as https://gist.github.com/JeffM2501/4c3a7e8a85302f743f8bd9dc1aae00ae?permalink_comment_id=5060959#gistcomment-5060959).

**Comment by JeffM2501** [comment]
you set ImGuiDockNodeFlags_PassthruCentralNode on the dockspace so that ImGui doesn't fill it with a gray panel.
I have updated the example to do this
