### ISSUE TITLE
Unable to specify FontAwesome font size

### ISSUE THREAD

**Issue by Julianiolo** [raylib-extras/rlImGui#69]
It is currently not possible to specify at which size the FontAwesome font is loaded.

In general, the way in which font loading is currently handled is somewhat unflexible, as the default font is always loaded (at the end of `rlImGuiBeginInitImGui`), and the fontawesome font is also always loaded (at the start of `rlImGuiEndInitImGui`). Maybe there should be flags which disable this default loading, so the user can load everything themself if they want to?

**Comment by JeffM2501** [comment]
There is, that's what the #define NO_FONT_AWESOME is for.
Define that, and build, then you can define your own fonts.
Look at https://github.com/raylib-extras/rlImGui/blob/main/examples/asset_browser/main.cpp, it does just that to load a big font awesome.
