### ISSUE TITLE
Examples fail to build on osx

### ISSUE THREAD

**Issue by MikeDX** [raylib-extras/rlImGui#72]
The asset browser and editor examples fail to compile on osx.

The editor example is due to deprecated functions on dear imgui 1.9.1

The asset browser fails due to stricmp not being available on osx (and possibly other posix systems)

I have created PR #71 to fix these issues.

**Comment by JeffM2501** [comment]
I have added a fix that includes some of your changes and makes rlImGui build with ImGui main branch
Thank you.
