### ISSUE TITLE
Can't see the images!

### ISSUE THREAD

**Issue by colesnicov** [raylib-extras/rlImGui#74]
Hi. I would like to let you know that after this [commit 'Use texture ID with ImGui so that the calling texture pointer can go …'](https://github.com/raylib-extras/rlImGui/commit/1dc076c2e8edf13bbf6860ba1029cc6286b5e384) I can't see the images. Both Image and ImageButton were affected. Only the black square image place. Linux/Ubuntu.

**Comment by JeffM2501** [comment]
do any of the examples work? like the editor example?

**Comment by colesnicov** [comment]
I could not run `rlImGui` as a separate project or example, just as a part of my project. I don't want to install `premake5` ...:/

**Comment by JeffM2501** [comment]
I reverted the change.
You don't need to install premake, it comes with the thing.
but you can just add the files to your build system, doesn't matter.
