### ISSUE TITLE
Probably triggers imgui asserts with sdl backend

### ISSUE THREAD

**Issue by jestarray** [raylib-extras/rlImGui#80]
https://github.com/raylib-extras/rlImGui/blob/89107354ea407970e24f6b9a5d6c54e2bebadf35/rlImGui.cpp#L641
https://github.com/ocornut/imgui/blob/master/imgui.cpp#L10459

I'm using a rust esque port of this impl imgui and it triggers this assert with backend set to SDL. I don't know if it happens in this C/C++ version but I'm going to assume so, otherwise close

**Comment by JeffM2501** [comment]
I need more info about what is happening. you are linking to a line in ImGui about tables,, that generally means you have a begin/end issue.

**Comment by jestarray** [comment]
Woops, looks like I didn't point it to a commit rather `master` which has changes to `imgui.cpp`
```
IM_ASSERT((g.IO.DeltaTime > 0.0f || g.FrameCount == 0)              && "Need a positive DeltaTime!");
```
Like I said, just try with SDL backend on raylib and you might get an assert. If you don't then close the issue

**Comment by Redesigner** [comment]
I just built raylib with the SDL2 backend and had this issue -- imgui asserts that DeltaTime is not greater than 0 (In this case, it is 0). Building raylib with GLFW doesn't trigger the assert. It seems to be an issue with how GetFrameTime() is calculated in raylib itself, but I'm not certain. I would think that GetFrameTime() returning 0 on the init step would be expected regardless of backend.

**Comment by JeffM2501** [comment]
I've pushed a change that won't send 0 to ImGui
