### ISSUE TITLE
WARNING: GetWindowScaleDPI() not implemented on target platform, when using raylib built with PLATFORM=SDL

### ISSUE THREAD

**Issue by Tarinaky** [raylib-extras/rlImGui#82]
When building raylib using PLATFORM_SDL I get WARNING: GetWindowScaleDPI() not implemented on target platform when ImGuiNewFrame is called.

I am able to work around this issue by commenting out all lines using the variable resolutionScale from this function, although this is not workable as an upstream solution.

I have tested this with raylib 5.5 preview (commit dd688d81a6a08bd205d57111a17f533705a3c4d1 'Thanks everyone for everything :D', which is the latest commit as of writing this)

I am building raylib with PLATFORM=SDL, which I believe sets PLATFORM_SDL inside raylib

Please let me know if there's any more information I can furnish you with.

**Comment by JeffM2501** [comment]
This is not an issue with rlImGui, but one with raylib. the fix here is to fix raylib to support that function, or at least not return and return 1,1.
rlImGui does not, and should not have special cases for specific raylib backends.
